---
root: true
env:
  'es2021': true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures: {}
extends:
  - airbnb
  - prettier
settings:
  import/core-modules: [electron]
rules:
  no-underscore-dangle: ['error', { 'allowAfterThis': true }]
